openapi: 3.0.3
info:
  title: Demos Example Process API
  version: '1.0'
  summary: |2+


    Created at 12/03/2023, 19:26

    ****




    # Changelog

    <details>
    <summary>CHANGELOG.md</summary>
    <p>


    All notable changes to this project will be documented in this file.

    * Types of Changes (L3):
      * Added: new features
      * Changed: changes in existing functionality
      * Deprecated: soon-to-be-removed features
      * Removed: now removed features
      * Fixed: any bug fixes
      * Security: in case of vulnerabilities


    The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
    and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

    ### Unreleased
    Initial Version

    </p>
    </details>

paths:
  /decisiondmn/singleEntryDMN/singleEntry/singleEntryDMN:
    head:
      tags:
      - singleEntryDMN
      summary: 'DecisionDmn: singleEntry'
      description: |2



        <details>
        <summary><b>Used in 1 Project(s) (EXPERIMENTAL)</b></summary>
        <p>


        - _dmn-scala_
           - [process](No URL defined for dmn-scala/OpenApi.html#operation/Process:%20process)




        </p>
        </details>
      operationId: 'DecisionDmn: singleEntry'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Input'
            examples:
              singleEntryDMN:
                value:
                  letter: A
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                oneOf:
                - type: integer
                  format: int32
              examples:
                singleEntryDMN:
                  value: 1
  /decisiondmn/collectEntriesDMN/collectEntries/collectEntriesDMN:
    head:
      tags:
      - collectEntriesDMN
      summary: 'DecisionDmn: collectEntries'
      description: |2



        <details>
        <summary><b>Used in 3 Project(s) (EXPERIMENTAL)</b></summary>
        <p>


        - _camundala_
           - [InvoiceReceiptP](No URL defined for camundala/OpenApi.html#operation/Process:%20InvoiceReceiptP)
           - [invoice](No URL defined for camundala/OpenApi.html#operation/Process:%20invoice)


        - _camundala-dsl_
           - [InvoiceReceiptP](No URL defined for camundala-dsl/OpenApi.html#operation/Process:%20InvoiceReceiptP)
           - [invoice](No URL defined for camundala-dsl/OpenApi.html#operation/Process:%20invoice)


        - _camundala-example_
           - [InvoiceReceiptP](No URL defined for camundala-example/OpenApi.html#operation/Process:%20InvoiceReceiptP)
           - [invoice](No URL defined for camundala-example/OpenApi.html#operation/Process:%20invoice)




        </p>
        </details>
      operationId: 'DecisionDmn: collectEntries'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Input'
            examples:
              collectEntriesDMN:
                value:
                  letter: A
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                oneOf:
                - type: integer
                  format: int32
              examples:
                collectEntriesDMN:
                  value:
                  - 1
                  - 2
  /decisiondmn/singleResultDMN/singleResult/singleResultDMN:
    head:
      tags:
      - singleResultDMN
      summary: 'DecisionDmn: singleResult'
      description: |2



        **Used in no other Process.**
      operationId: 'DecisionDmn: singleResult'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Input'
            examples:
              singleResultDMN:
                value:
                  letter: A
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SingleResult_camundala.examples.demos.DecisionResultTypes.ManyOutResult[]'
              examples:
                singleResultDMN:
                  value:
                    index: 1
                    emoji: ðŸ¤©
  /decisiondmn/resultListDMN/resultList/resultListDMN:
    head:
      tags:
      - resultListDMN
      summary: 'DecisionDmn: resultList'
      description: |2



        **Used in no other Process.**
      operationId: 'DecisionDmn: resultList'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Input'
            examples:
              resultListDMN:
                value:
                  letter: A
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultList_camundala.examples.demos.DecisionResultTypes.ManyOutResult[]'
              examples:
                resultListDMN:
                  value:
                  - index: 1
                    emoji: ðŸ¤©
                  - index: 2
                    emoji: ðŸ˜‚
  /process/demoProcess/just-for-demo/demoProcess:
    head:
      tags:
      - demoProcess
      summary: 'Process: just-for-demo'
      description: |2



        **Used in no other Process.**

        **Uses no other Processes.**
      operationId: 'Process: just-for-demo'
      responses:
        '200':
          description: ''
  /decisiondmn/demoProcess/singleEntry/singleEntryDMN:
    head:
      tags:
      - demoProcess
      summary: 'DecisionDmn: singleEntry'
      description: |2



        <details>
        <summary><b>Used in 1 Project(s) (EXPERIMENTAL)</b></summary>
        <p>


        - _dmn-scala_
           - [process](No URL defined for dmn-scala/OpenApi.html#operation/Process:%20process)




        </p>
        </details>
      operationId: 'DecisionDmn: singleEntry'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Input'
            examples:
              singleEntryDMN:
                value:
                  letter: A
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                oneOf:
                - type: integer
                  format: int32
              examples:
                singleEntryDMN:
                  value: 1
  /decisiondmn/demoProcess/collectEntries/collectEntriesDMN:
    head:
      tags:
      - demoProcess
      summary: 'DecisionDmn: collectEntries'
      description: |2



        <details>
        <summary><b>Used in 3 Project(s) (EXPERIMENTAL)</b></summary>
        <p>


        - _camundala_
           - [InvoiceReceiptP](No URL defined for camundala/OpenApi.html#operation/Process:%20InvoiceReceiptP)
           - [invoice](No URL defined for camundala/OpenApi.html#operation/Process:%20invoice)


        - _camundala-dsl_
           - [InvoiceReceiptP](No URL defined for camundala-dsl/OpenApi.html#operation/Process:%20InvoiceReceiptP)
           - [invoice](No URL defined for camundala-dsl/OpenApi.html#operation/Process:%20invoice)


        - _camundala-example_
           - [InvoiceReceiptP](No URL defined for camundala-example/OpenApi.html#operation/Process:%20InvoiceReceiptP)
           - [invoice](No URL defined for camundala-example/OpenApi.html#operation/Process:%20invoice)




        </p>
        </details>
      operationId: 'DecisionDmn: collectEntries'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Input'
            examples:
              collectEntriesDMN:
                value:
                  letter: A
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                oneOf:
                - type: integer
                  format: int32
              examples:
                collectEntriesDMN:
                  value:
                  - 1
                  - 2
  /decisiondmn/demoProcess/singleResult/singleResultDMN:
    head:
      tags:
      - demoProcess
      summary: 'DecisionDmn: singleResult'
      description: |2



        **Used in no other Process.**
      operationId: 'DecisionDmn: singleResult'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Input'
            examples:
              singleResultDMN:
                value:
                  letter: A
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SingleResult_camundala.examples.demos.DecisionResultTypes.ManyOutResult[]'
              examples:
                singleResultDMN:
                  value:
                    index: 1
                    emoji: ðŸ¤©
  /decisiondmn/demoProcess/resultList/resultListDMN:
    head:
      tags:
      - demoProcess
      summary: 'DecisionDmn: resultList'
      description: |2



        **Used in no other Process.**
      operationId: 'DecisionDmn: resultList'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Input'
            examples:
              resultListDMN:
                value:
                  letter: A
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultList_camundala.examples.demos.DecisionResultTypes.ManyOutResult[]'
              examples:
                resultListDMN:
                  value:
                  - index: 1
                    emoji: ðŸ¤©
                  - index: 2
                    emoji: ðŸ˜‚
  /process/enumExample/enum-example/enumExample:
    head:
      tags:
      - enumExample
      summary: 'Process: enum-example'
      description: |2



        **Used in no other Process.**

        **Uses no other Processes.**
      operationId: 'Process: enum-example'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Input1'
            examples:
              enumExample:
                value:
                  someValue: hello
                  simpleEnum: One
                  customMock:
                    intValue: 12
                    simpleEnum: One
                    type: A
                  type: A
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Output'
              examples:
                enumExample:
                  value:
                    intValue: 12
                    simpleEnum: One
                    type: A
  /decisiondmn/DateExampleDMN/DateExample/DateExampleDMN:
    head:
      tags:
      - DateExampleDMN
      summary: 'DecisionDmn: DateExample'
      description: |2



        **Used in no other Process.**
      operationId: 'DecisionDmn: DateExample'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Input2'
            examples:
              DateExampleDMN:
                value:
                  inDate: '2013-12-12T12:12:12'
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                oneOf:
                - type: string
              examples:
                DateExampleDMN:
                  value: 2012-12-12T12:12:12.000+0100
  /decisiondmn/VariablesExampleDMN/VariablesExample/VariablesExampleDMN:
    head:
      tags:
      - VariablesExampleDMN
      summary: 'DecisionDmn: VariablesExample'
      description: |2



        **Used in no other Process.**
      operationId: 'DecisionDmn: VariablesExample'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Input3'
            examples:
              VariablesExampleDMN:
                value:
                  letters: A_dynamic_2
                  inputVariable: dynamic
                  outputVariable: dynamicOut
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                oneOf:
                - type: string
              examples:
                VariablesExampleDMN:
                  value: OK dynamicOut
components:
  schemas:
    A:
      required:
      - simpleEnum
      type: object
      properties:
        someValue:
          type: string
        simpleEnum:
          $ref: '#/components/schemas/SimpleEnum'
        customMock:
          $ref: '#/components/schemas/Output'
    A1:
      required:
      - intValue
      - simpleEnum
      type: object
      properties:
        intValue:
          type: integer
          format: int32
        simpleEnum:
          $ref: '#/components/schemas/SimpleEnum'
    Input:
      required:
      - letter
      type: object
      properties:
        letter:
          type: string
    Input1:
      oneOf:
      - $ref: '#/components/schemas/A'
    Input2:
      required:
      - inDate
      type: object
      properties:
        inDate:
          type: string
    Input3:
      required:
      - letters
      - inputVariable
      - outputVariable
      type: object
      properties:
        letters:
          type: string
        inputVariable:
          oneOf:
          - type: string
        outputVariable:
          oneOf:
          - type: string
    ManyOutResult:
      required:
      - index
      - emoji
      type: object
      properties:
        index:
          type: integer
          format: int32
        emoji:
          type: string
    One:
      type: object
    Output:
      oneOf:
      - $ref: '#/components/schemas/A1'
    ResultList_camundala.examples.demos.DecisionResultTypes.ManyOutResult[]:
      oneOf:
      - $ref: '#/components/schemas/ManyOutResult'
    SimpleEnum:
      oneOf:
      - $ref: '#/components/schemas/One'
      - $ref: '#/components/schemas/Two'
    SingleResult_camundala.examples.demos.DecisionResultTypes.ManyOutResult[]:
      oneOf:
      - $ref: '#/components/schemas/ManyOutResult'
    Two:
      type: object
